files:
  include: 'src/**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth: 1
  border-zero: 1
  brace-style:
    - 1
    - style: '1tbs'
      allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths:
    - 1
    - leading-underscore: false
      filename-extension: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  function-name-format:
    - 1
    - convention hyphenatedbem
  hex-length:
    - 1
    - style: long
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 1
    - size: 2
  leading-zero: 1
  mixin-name-format: 1
  mixins-before-declarations:
    - 1
    - exclude: ['breakpoint', 'mq']
  no-color-keywords: 1
  no-color-literals: 1
  #no-css-comments: 1
  #no-extends: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    - allow-element-with-id: true
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-url-protocols: 1
  #no-vendor-prefixes: 1
  one-declaration-per-line: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  quotes:
    - 1
    - style: simples
  single-line-per-selector: 1
  space-after-bang: 1
  space-after-colon: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      # example: variable-name | block---variable | block--modifier---variable | block__element---variable | block--modifier__element---variable
      convention: ^([a-z0-9]+(-[a-z0-9]+)*|[a-z](\-?[a-z0-9]+)*((--|__)[a-z0-9](\-?[a-z0-9]+)*)*(---[a-z0-9]+(-[a-z0-9]+)*))$
  zero-unit: 1
